language: generic

sudo: required

services:
  - mysql

brew_packages:
  - pyenv

before_install:
  - sudo service postgresql restart
  - psql -c "create database timetracker;" -U postgres && psql -c "create user timetracker password 'timetracker';" -U postgres
  - pyenv versions && pyenv install 3.6.3 -f && pyenv global 3.6.3

install: pip install -Ur requirements.txt

jobs:
  include:
      - stage: test
        env: DB_TYPE=sqlite
        os: linux
        before_script: python3 ci_configurator.py
        script: python3 -m timetracker --test
        after_script: cat config.json
      - stage: test
        env: DB_TYPE=postgres
        os: linux
        before_script: python3 ci_configurator.py
        script: python3 -m timetracker --test
        after_script: cat config.json
      - stage: test
        env: DB_TYPE=mysql
        os: linux
        before_script: python3 ci_configurator.py
        script: python3 -m timetracker --test
        after_script: cat config.json
      - stage: deploy
        script: pyinstaller -F timetracker.spec
        os: linux
      - stage: deploy
        script: pyinstaller -F timetracker.spec
        os: osx
