language: generic

sudo: required

dist: xenial

osx_image: xcode10.2

services:
  - mysql
  - postgresql

addons:
  homebrew:
    update: true
    packages:
      - pyenv
      - mysql

install: pyenv versions && pyenv install 3.6.7 -s && pyenv global 3.6.7 && pip install -Ur requirements.txt

jobs:
  include:
      - stage: test
        env: DB_TYPE=sqlite
        os: linux
        before_script: python3 ci_configurator.py
        script: python3 -m timetracker --test
      - stage: test
        env: DB_TYPE=postgres
        os: linux
        before_install: psql -f ci_pg.sql -U postgres
        before_script: python3 ci_configurator.py
        script: python3 -m timetracker --test
      - stage: test
        env: DB_TYPE=mysql
        os: linux
        before_install: cat ci_mysql.sql | mysql mysql -v && sudo service mysql restart
        before_script: python3 ci_configurator.py
        script: python3 -m timetracker --test
        after_script: mysqldump --databases timetracking
      - stage: deploy
        script: ./build.sh
        os: linux
      - stage: deploy
        script: ./build.sh
        os: osx

notifications:
  email: false

deploy:
