language: generic

sudo: required

services:
  - postgresql
  - mysql

os:
  - osx
  - linux

env:
  - DB_TYPE=sqlite
  - DB_TYPE=postgres
  - DB_TYPE=mysql

brew_packages:
  - pyenv

before_install: pyenv versions && pyenv install 3.6.3 -y && pyenv global 3.6.4
install: pip install -Ur requirements.txt


before_script: python3 ci_configurator.py
script: python3 -m timetracker --test
after_script: cat config.json

