language: generic

jobs:
  include:
    - stage: "Testing"

      sudo: required

      os: linux

      env:
        matrix:
          - DB_TYPE=sqlite
          - DB_TYPE=postgres
          - DB_TYPE=mysql

      brew_packages:
        - pyenv

      apt_packages:
        - mysql-server
        - mysql-client

      before_install:
        - sudo service mysql restart
        - sudo service postgresql restart
        - psql -c "create database timetracker;" -U postgres && psql -c "create user timetracker password 'timetracker';" -U postgres
        - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('timetracker') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
        - sudo mysql_upgrade -u root -pnew_password
        - sudo service mysql restart
        - pyenv versions && pyenv install 3.6.3 -f && pyenv global 3.6.3

      install: pip install -Ur requirements.txt

      before_script: python3 ci_configurator.py

      script: python3 -m timetracker --test

      after_script: cat config.json

    - stage: "Build Binaries"
      os:
        - linux
        - osx
      install: pyenv versions && pyenv install 3.6.3 -f && pyenv global 3.6.3 && pip install -Ur requirements.txt
      script: pyinstaller timetracker/__main__.py -F



