language: python

sudo: required

services:
  - postgresql
  - mysql

os:
  - osx
  - linux

env:
  - DB_TYPE=sqlite
  - DB_TYPE=postgres
  - DB_TYPE=mysql
  -
before_install: curl https://pyenv.run | bash && pyenv install 3.7.3 && pyenv global 3.7.3
install: pip install -Ur requirements.txt

before_script: python3 ci_configurator.py
script: python3 -m timetracker --test
after_script: cat config.json