language: generic

sudo: required

dist: xenial

osx_image: xcode10.2

services:
- mysql
- postgresql

addons:
  homebrew:
    update: true
    packages:
    - pyenv
    - mysql
    - zlib
    - xz

install: pyenv versions && pyenv install 3.6.7 -s && pyenv global 3.6.7 && pip install -Ur requirements.txt

jobs:
  include:
  - stage: test
    env: DB_TYPE=sqlite
    os: linux
    before_script: python3 ci_configurator.py
    script: python3 -m timetracker --test
    deploy: false

  - stage: test
    env: DB_TYPE=postgres
    os: linux
    before_install: psql -f ci_pg.sql -U postgres
    before_script: python3 ci_configurator.py
    script: python3 -m timetracker --test
    deploy: false

  - stage: test
    env: DB_TYPE=mysql
    os: linux
    before_install: cat ci_mysql.sql | mysql mysql -v && sudo service mysql restart
    before_script: python3 ci_configurator.py
    script: python3 -m timetracker --test
    after_script: mysqldump --databases timetracking
    deploy: false


  - stage: deploy
    script: "./build.sh"
    after_success: rename dist/timetracker dist/timetracker-linux
    os: linux

  - stage: deploy
    script: "./build.sh"
    before_install: xcode-select --install
    after_success: rename dist/timetracker dist/timetracker-macos
    os: osx

notifications:
  email: false

deploy:
  provider: releases
  api_key:
    secure: ZnoHybCmh0jEigr5vvf7pVrQ3efDlWytf8SFUj7eMZMRRzxieQ4HFYnpyl2TfFg7IZLkEBJrptfRbUVygHfMp2lAGLtERQPSFrV+QBOiWlo2QGK2n4c1Vh7IVg0D4PgQepKN4SvdFSByysO0w3rg+PbF8XC9MLot3wvLXDABsra1RBcU4vG8X2NROHguyXQDK1TFpVEeaeS/6xjJgRLGBHUQNC2xNJ3lGaJtxaHOrvXAZutKP1N/WwHUF0DgNHlGb1SvY9zgkL9u0lN01oqxkon7zsLpiM8bg1N9f9sM7mJy6i+npf9RUTcitgHumQNg5ADn+tyNgeng9XFWSIE+PpQ94RZtpjLGZjtf6eNA5zh23yk61TXeMYZnqmJDZK9p7rgHn8ZCxBvhSyEEiPDXaZrbRXPwYyWbB5DSZBQzsJceUGaCy0g0L0jNk6aQ71bs5SqGNjKo6eifgnp9Yj5BuWTUy++r8TytyuBf997w+G2dQtZIZYKiYsTw0QT3AD7/lOzYS/R+fPRS3uUFWzrXGOiqs2S5Y1RCyEboPizfLTNQ4JqANpMRbcNQdC7ZM0y+AwGTKhv9WFCct7Z0jLePWuV1hTpWZXkO7crVrop8E0/u2OjGvtMUzVY6d4+raQ2qkhNTzvSGYCc31DYVv80DjhPKfBTl9p8KuxutJTgvwHw=
  file: dist/timetracker-$TRAVIS_OS_NAME
  on:
    repo: tweirtx/timetracker
    tags: true
