services:
  - mssql2017

environment:
  DB_TYPE: mssql

test_script:
  - cmd: C:\Python36-x64\python -m timetracker --test

install:
  - C:\Python36-x64\Scripts\pip install -Ur requirements.txt
  - C:\Python36-x64\python ci_configurator.py

build: off

after_test:
  - type config.json

  #build_script:
#  - pyinstaller -F timetracker.spec