services:
  - mssql2017

environment:
  DB_TYPE: mssql

test_script:
  - cmd: dist\timetracker.exe --test

install:
  - C:\Python36-x64\Scripts\pip install -Ur requirements.txt
  - C:\Python36-x64\python ci_configurator.py


build_script:
  - C:\Python36-x64\Scripts\pyinstaller -F timetracker.spec

deploy:
  - provider: GitHub
    auth_token:
      secure: nESUbdF6Dm6zQNu98xP8XwgDxtlCc3lqh8b33bNUMRdf4hAd5KoyV74VnkMYOYwa
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
    artifacts: timetracker.exe

before_deploy:
  - cmd: move dist\timetracker.exe timetracker.exe