services:
  - mssql2017

environment:
  DB_TYPE: mssql

test_script:
  - cmd: C:\Python36-x64\python -m timetracker --test
  - cmd: dist/timetracker.exe --test

install:
  - C:\Python36-x64\Scripts\pip install -Ur requirements.txt
  - C:\Python36-x64\python ci_configurator.py


build_script:
  - C:\Python36-x64\Scripts\pyinstaller -F timetracker.spec