services:
  - mssql2017

environment:
  DB_TYPE: mssql

test_script:
  - cmd: C:\Python36\python -m timetracker --test

install:
  - C:\Python36\Scripts\pip install -Ur requirements.txt
  - C:\Python36\python ci_configurator.py
